<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGRLf13O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGRLf13O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGRLf13O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGRLf13O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGRLf13O\App_KernelDevDebugContainer([
    'container.build_hash' => 'GRLf13O',
    'container.build_id' => '61dd4015',
    'container.build_time' => 1725284276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGRLf13O');
