<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO2hhO67\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO2hhO67/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO2hhO67.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO2hhO67\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO2hhO67\App_KernelDevDebugContainer([
    'container.build_hash' => 'O2hhO67',
    'container.build_id' => '76a6db0b',
    'container.build_time' => 1724835410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO2hhO67');
