<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDGfaMi4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDGfaMi4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDGfaMi4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDGfaMi4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDGfaMi4\App_KernelDevDebugContainer([
    'container.build_hash' => 'DGfaMi4',
    'container.build_id' => '117bfc5a',
    'container.build_time' => 1725030497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDGfaMi4');
