<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.61b1725c.js',
                'build/751.ef545eca.js',
                'build/app.0784ad4d.js',
            ],
            'css' => [
                'build/app.fe7ed34b.css',
            ],
        ],
    ],
],

]];
